### ISSUE TITLE
what is difference between delete_in_advance and replace?

### ISSUE THREAD

**Issue by sshkim** [embulk/embulk-output-bigquery#124]
I'm using this plugin very well. But I have something being curious. What is difference between `delete_in_advance` and `replace` in mode? 

**Situation is like below.**
I'm migrationing to bigquery. But the job is full dump so I think `delete_in_advance` is more closer than `replace`. 
But I got same result about two of both. 
Please let me know what is difference.

**Comment by hiroyuki-sato** [comment]
Hello, @sshkim 

This description may help. `replace` uses temporary table.

https://github.com/embulk/embulk-output-bigquery#replace

**Comment by sshkim** [comment]
> Hello, @sshkim
> 
> This description may help. `replace` uses temporary table.
> 
> https://github.com/embulk/embulk-output-bigquery#replace

Thanks for your reply.

But I already read the document. But I can't understand what is difference.

In my situation is like this, not partitioning table to migrate from mysql to Bigquery.

Then what is difference, `I think the result is same.` But processing might be different...?

Thank you. And which one is better? (maybe if you let me know the processing, I can understand.)

**Comment by sonots** [comment]
Right, result is same, but processing is different.

delete_in_advance: The table would become empty after (1) and before (2). This is easy implementation, but usually not desired. If another batch which reads the table while embulk is running with delete_in_advance, the another batch may reads an empty table or a table with a few rows on the gap timing between (1) and (2).

* (1) delete
* (2) insert

replace: In the case of replace, because we use an atomic operation, there is no gap timing which a table becomes empty or with a few rows. The behavior is very expected to build robust data engineering. 

* (1) creates temp table
* (2) replace target table with the temp table with an atomic operation

replace mode is recommended.

**Comment by sshkim** [comment]
Thanks everyone. I got understand this issue.
